# Generated by Django 5.0 on 2024-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('avalible', models.BooleanField(verbose_name='Disponible')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Foto')),
            ],
        ),
    ]
